version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: easymirror-platform-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
